
    list1.printLL()
    print("-------------")
    list1.length()
    print("-------------")
    list1.removebegin()
    list1.printLL()
    print("-------------")
    list1.removelast()
    list1.printLL()
    list1.insertatbegin(1)
    list1.insertatbegin(2)
    list1.insertatend(3)
    list1.printrev()